name: Create and push
on: push

jobs:
  build-and-push-s3:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Setup Docker
        uses: docker/setup-buildx-action@v3 
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:docker-image/v1.16/debian-s3/"
          file: Dockerfile
          push: true
          tags: registry.techdebt.cloud/debian-fluentd-s3:${{github.sha}}